---
apiVersion: v1
kind: Service
metadata:
  name: pselasticsearch
  labels:
    app: pselasticsearch
    component: pselasticsearch
    role: master
spec:
  type: ClusterIP
  selector:
    component: pselasticsearch
    role: master
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pselasticsearch-discovery
  labels:
    app: pselasticsearch
    component: pselasticsearch
    role: master
spec:
  type: ClusterIP
  selector:
    component: pselasticsearch
    role: master
  ports:
    - name: transport
      port: 9300
      protocol: TCP
